// <auto-generated />
using EmpresaImportadoraDC.Models.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpresaImportadoraDC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CorreoElectronico");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroCasillero")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoEstado")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            TipoEstado = "En Bodega Miami"
                        },
                        new
                        {
                            EstadoId = 2,
                            TipoEstado = "En tránsito a Colombia"
                        },
                        new
                        {
                            EstadoId = 3,
                            TipoEstado = "En bodega Colombia"
                        },
                        new
                        {
                            EstadoId = 4,
                            TipoEstado = "En tránsito a dirección del cliente"
                        },
                        new
                        {
                            EstadoId = 5,
                            TipoEstado = "Entregado"
                        });
                });

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.Mercancia", b =>
                {
                    b.Property<int>("MercanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoMercancia")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MercanciaId");

                    b.ToTable("Mercancia");

                    b.HasData(
                        new
                        {
                            MercanciaId = 1,
                            TipoMercancia = "Frágil"
                        },
                        new
                        {
                            MercanciaId = 2,
                            TipoMercancia = "Pesadas"
                        },
                        new
                        {
                            MercanciaId = 3,
                            TipoMercancia = "Peligrosas"
                        },
                        new
                        {
                            MercanciaId = 4,
                            TipoMercancia = "Perecederas"
                        });
                });

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.Paquete", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("MercanciaId")
                        .HasColumnType("int");

                    b.Property<int>("NoGuiaCO")
                        .HasColumnType("int");

                    b.Property<int>("NoGuiaUSA")
                        .HasColumnType("int");

                    b.Property<int>("PesoLibras")
                        .HasColumnType("int");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportadoraCO")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransportadoraUSA")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ValorTotal")
                        .HasColumnType("bigint");

                    b.HasKey("PaqueteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MercanciaId");

                    b.ToTable("Paquete");
                });

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.Transportadora", b =>
                {
                    b.Property<int>("TransportadoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TransportadoraId");

                    b.ToTable("Transportadora");
                });

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.ValorLibra", b =>
                {
                    b.Property<int>("ValorLibraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ValorLi")
                        .HasColumnType("int");

                    b.HasKey("ValorLibraId");

                    b.ToTable("ValorLibra");

                    b.HasData(
                        new
                        {
                            ValorLibraId = 1,
                            ValorLi = 0
                        });
                });

            modelBuilder.Entity("EmpresaImportadoraDC.Models.Entities.Paquete", b =>
                {
                    b.HasOne("EmpresaImportadoraDC.Models.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpresaImportadoraDC.Models.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpresaImportadoraDC.Models.Entities.Mercancia", "Mercancia")
                        .WithMany()
                        .HasForeignKey("MercanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Mercancia");
                });
#pragma warning restore 612, 618
        }
    }
}
